# Generated by Django 3.2 on 2021-05-05 15:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_purchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchased',
            name='date_ordered',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
