# Generated by Django 3.2 on 2021-05-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_purchaseditems_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseditems',
            name='order_id',
        ),
        migrations.AddField(
            model_name='purchased',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
