# Generated by Django 3.2 on 2021-05-06 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_alter_purchaseditems_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchased',
            name='address',
        ),
        migrations.RemoveField(
            model_name='purchased',
            name='city',
        ),
        migrations.RemoveField(
            model_name='purchased',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='purchased',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='purchased',
            name='state',
        ),
        migrations.RemoveField(
            model_name='purchased',
            name='zipcode',
        ),
    ]
