# Generated by Django 3.2 on 2021-05-05 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_remove_purchaseditems_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseditems',
            name='order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.purchased'),
        ),
    ]
