# Generated by Django 3.2 on 2021-05-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_alter_purchasedorder_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedorder',
            name='date_ordered',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
