# Generated by Django 3.2 on 2021-05-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0048_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='purchasedorder',
            old_name='price',
            new_name='total_price',
        ),
        migrations.AddField(
            model_name='product',
            name='SKUID',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='purchasedorder',
            name='GSTIN',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
