# Generated by Django 3.0.14 on 2021-05-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0049_auto_20210515_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detail',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='specs',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
