# Generated by Django 3.2 on 2021-05-16 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0054_auto_20210516_1302'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
