# Generated by Django 3.2 on 2021-05-16 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0056_shippingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseditems',
            name='purchased_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.purchasedorder'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='purchased_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.purchasedorder'),
        ),
    ]
