# Generated by Django 3.2 on 2021-05-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0057_auto_20210516_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedorder',
            name='COD',
            field=models.IntegerField(choices=[(1, 'SUCCESS'), (2, 'PENDING/FAILURE')], default=2),
        ),
        migrations.AlterField(
            model_name='purchasedorder',
            name='payment_status',
            field=models.IntegerField(choices=[(1, 'YES'), (2, 'NO')], default=2),
        ),
    ]
