# Generated by Django 3.2 on 2021-05-20 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0061_alter_orderitem_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
