# Generated by Django 3.2 on 2021-04-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210422_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='mobile',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
