# Generated by Django 3.2 on 2021-05-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_purchased_date_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchased',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
