# Generated by Django 3.2 on 2021-05-05 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_purchaseeditems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PurchaseedItems',
            new_name='PurchasedItems',
        ),
    ]
