# Generated by Django 3.2 on 2021-05-05 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_rename_purchaseeditems_purchaseditems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseditems',
            name='order_id',
        ),
    ]
