# Generated by Django 3.2 on 2021-05-06 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_rename_quantity_purchased_cart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseditems',
            name='product',
        ),
    ]
