# Generated by Django 3.2 on 2021-05-06 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_auto_20210506_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseditems',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.purchased'),
        ),
    ]
