# Generated by Django 3.2 on 2021-05-07 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_alter_shippingaddress_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Purchased',
            new_name='PurchasedOrder',
        ),
        migrations.RenameField(
            model_name='purchaseditems',
            old_name='order',
            new_name='purchased_order',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='order',
            new_name='purchased_order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_signature',
        ),
    ]
