# Generated by Django 3.2 on 2021-05-07 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_auto_20210507_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedorder',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
