# Generated by Django 3.2 on 2021-05-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_auto_20210507_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedorder',
            name='payment_status',
            field=models.IntegerField(choices=[(1, 'SUCCESS'), (2, 'FAILURE'), (3, 'PENDING')], default=3),
        ),
    ]
