# Generated by Django 3.2 on 2021-05-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_purchasedorder_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedorder',
            name='payment_status',
            field=models.IntegerField(choices=[(1, 'SUCCESS'), (2, 'PENDING/FAILURE')], default=2),
        ),
    ]
