# Generated by Django 3.2 on 2021-05-08 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_alter_purchasedorder_date_ordered'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
